In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
df=pd.read_csv("/content/insurance_data.csv")

In [5]:
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=42)

In [7]:
df.shape

(28, 3)

In [8]:
 x_train.shape

(22, 2)

In [9]:
x_train['age']=x_train['age']/100
x_test['age']=x_test['age']/100

In [10]:
x_train

age  affordibility
17  0.58              1
22  0.40              1
11  0.28              1
13  0.29              0
15  0.55              1
1   0.25              0
4   0.46              1
5   0.56              1
2   0.47              1
16  0.25              0
23  0.45              1
3   0.52              0
26  0.23              1
24  0.50              1
18  0.19              0
27  0.46              1
20  0.21              1
7   0.60              0
10  0.18              1
14  0.49              1
19  0.18              1
6   0.55              0

In [11]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])

In [12]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [13]:
model.fit(x_train,y_train,epochs=5000)

Streaming output truncated to the last 5000 lines.
Epoch 2011/5000
1/1 [==============================] - 0s 10ms/step - loss: 0.5791 - accuracy: 0.8182
Epoch 2012/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.5791 - accuracy: 0.8182
Epoch 2013/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.5791 - accuracy: 0.8182
Epoch 2014/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.5790 - accuracy: 0.8182
Epoch 2015/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.5790 - accuracy: 0.8182
Epoch 2016/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.5789 - accuracy: 0.8182
Epoch 2017/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.5789 - accuracy: 0.8182
Epoch 2018/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.5789 - accuracy: 0.8182
Epoch 2019/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.5788 - accuracy: 0.8182
Epoch 2020/5000
1/1 [==================

In [14]:
model.evaluate(x_test,y_test)

1/1 [==============================] - 0s 214ms/step - loss: 0.2647 - accuracy: 1.0000


[0.26470303535461426, 1.0]

In [15]:
model.predict(x_test)

1/1 [==============================] - 0s 110ms/step


array([[0.81626713],
       [0.75767547],
       [0.8236742 ],
       [0.18819511],
       [0.38559136],
       [0.1959822 ]], dtype=float32)

In [16]:
ceoff,bias=model.get_weights()

In [17]:
ceoff

array([[5.0183096],
       [1.1966311]], dtype=float32)

In [18]:
bias

array([-2.7665412], dtype=float32)

Neural Network from scratch

In [19]:
import math
def sigmoid(x):
  return 1/(1+math.exp(-x))

sigmoid(10)

0.9999546021312976

In [20]:
def prediction_function(age,affordability):
  weighted_sum=ceoff[0]*age + ceoff[1]*affordability + bias
  return sigmoid(weighted_sum)

In [21]:
prediction_function(47,1)

1.0

In [22]:
def log_loss(y_true,y_pred):
  epsilon=1e-15
  y_pred_new=[max(i,epsilon) for i in y_pred]
  y_pred_new=[min(i,1-epsilon) for i in y_pred_new]
  y_pred_new=np.array(y_pred_new)
  return -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))

In [23]:
def sigmoid_numpy(x): #vector sigmoid
  return 1/(1+np.exp(-x))

sigmoid_numpy(np.array([34,5,6]))

array([1.        , 0.99330715, 0.99752738])

In [24]:
def gradient(age,affordability,y_true,epochs):
  w1=w2=1
  bias=0
  learning_rate=0.5
  n=len(age)

  for i in range(epochs):
    weighted_sum= w1*age+w2*affordability + bias
    y_pred = sigmoid_numpy(weighted_sum)

    loss = log_loss(y_true,y_pred)

    w1d=(1/n)*np.dot(np.transpose(age),(y_pred-y_true))
    w2d=(1/n)*np.dot(np.transpose(affordability),(y_pred-y_true))

    bias=np.mean(y_pred-y_true)

    w1=w1-learning_rate*w1d
    w2=w2-learning_rate*w2d
    bias=bias-learning_rate*bias

    print("epoch",epochs,"w1:",w1,"w2:",w2,"bias:",bias,"loss:",loss)
  return w1,w2,bias

In [25]:
x_train

age  affordibility
17  0.58              1
22  0.40              1
11  0.28              1
13  0.29              0
15  0.55              1
1   0.25              0
4   0.46              1
5   0.56              1
2   0.47              1
16  0.25              0
23  0.45              1
3   0.52              0
26  0.23              1
24  0.50              1
18  0.19              0
27  0.46              1
20  0.21              1
7   0.60              0
10  0.18              1
14  0.49              1
19  0.18              1
6   0.55              0

In [26]:
gradient(x_train['age'],x_train['affordibility'],y_train,1000)

epoch 1000 w1: 0.9736899318847281 w2: 0.931388810977659 bias: 0.11748951666770448 loss: 0.7428288579142563
epoch 1000 w1: 0.9451118851750457 w2: 0.8607095927712907 bias: 0.12362393508082584 loss: 0.7601580672581679
epoch 1000 w1: 0.9182454813119643 w2: 0.794123618395027 bias: 0.1193619465536651 loss: 0.7503599662761239
epoch 1000 w1: 0.8934289728218214 w2: 0.7321451564046372 bias: 0.11421954066441536 loss: 0.7394123517305228
epoch 1000 w1: 0.8706432596225366 w2: 0.6747168527707559 bias: 0.10912796190485136 loss: 0.7296793426456272
epoch 1000 w1: 0.8498204947633821 w2: 0.6216917543669043 bias: 0.10421179051690528 loss: 0.7212543136973335
epoch 1000 w1: 0.8308764795759052 w2: 0.5728867834379855 bias: 0.09951130753272559 loss: 0.7140236164840265
epoch 1000 w1: 0.8137166014988223 w2: 0.5280944842745564 bias: 0.09505161325877962 loss: 0.7078559150532908
epoch 1000 w1: 0.7982390969129121 w2: 0.4870904202937349 bias: 0.09084964450650747 loss: 0.7026228739302058
epoch 1000 w1: 0.78433786179521

(0.986296183064828, -0.03785929183080954, 0.050608543226397545)