In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv("/content/insurance_data.csv")

In [3]:
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=42)

In [5]:
df.shape

(28, 3)

In [6]:
 x_train.shape

(22, 2)

In [7]:
x_train['age']=x_train['age']/100
x_test['age']=x_test['age']/100

In [8]:
x_train

age  affordibility
17  0.58              1
22  0.40              1
11  0.28              1
13  0.29              0
15  0.55              1
1   0.25              0
4   0.46              1
5   0.56              1
2   0.47              1
16  0.25              0
23  0.45              1
3   0.52              0
26  0.23              1
24  0.50              1
18  0.19              0
27  0.46              1
20  0.21              1
7   0.60              0
10  0.18              1
14  0.49              1
19  0.18              1
6   0.55              0

In [9]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])

In [10]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [11]:
model.fit(x_train,y_train,epochs=50)

Epoch 1/50
1/1 [==============================] - 1s 749ms/step - loss: 0.7428 - accuracy: 0.5000
Epoch 2/50
1/1 [==============================] - 0s 14ms/step - loss: 0.7424 - accuracy: 0.5000
Epoch 3/50
1/1 [==============================] - 0s 12ms/step - loss: 0.7420 - accuracy: 0.5000
Epoch 4/50
1/1 [==============================] - 0s 13ms/step - loss: 0.7416 - accuracy: 0.5000
Epoch 5/50
1/1 [==============================] - 0s 11ms/step - loss: 0.7411 - accuracy: 0.5000
Epoch 6/50
1/1 [==============================] - 0s 10ms/step - loss: 0.7407 - accuracy: 0.5000
Epoch 7/50
1/1 [==============================] - 0s 10ms/step - loss: 0.7403 - accuracy: 0.5000
Epoch 8/50
1/1 [==============================] - 0s 11ms/step - loss: 0.7399 - accuracy: 0.5000
Epoch 9/50
1/1 [==============================] - 0s 10ms/step - loss: 0.7395 - accuracy: 0.5000
Epoch 10/50
1/1 [==============================] - 0s 16ms/step - loss: 0.7390 - accuracy: 0.5000
Epoch 11/50
1/1 [===========

In [12]:
model.evaluate(x_test,y_test)

1/1 [==============================] - 0s 183ms/step - loss: 0.6033 - accuracy: 0.5000


[0.6032715439796448, 0.5]

In [13]:
model.predict(x_test)

1/1 [==============================] - 0s 71ms/step


array([[0.8147441 ],
       [0.80448633],
       [0.81617504],
       [0.5492696 ],
       [0.75218296],
       [0.5516227 ]], dtype=float32)

In [14]:
ceoff,bias=model.get_weights()

In [15]:
ceoff

array([[0.9508901],
       [0.9506045]], dtype=float32)

In [16]:
bias

array([-0.0495113], dtype=float32)

Neural Network from scratch

In [17]:
import math
def sigmoid(x):
  return 1/(1+math.exp(-x))

sigmoid(10)

0.9999546021312976

In [18]:
def prediction_function(age,affordability):
  weighted_sum=ceoff[0]*age + ceoff[1]*affordability + bias
  return sigmoid(weighted_sum)

In [19]:
prediction_function(47,1)

1.0

In [20]:
def log_loss(y_true,y_pred):
  epsilon=1e-15
  y_pred_new=[max(i,epsilon) for i in y_pred]
  y_pred_new=[min(i,1-epsilon) for i in y_pred_new]
  y_pred_new=np.array(y_pred_new)
  return -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))

In [37]:
def sigmoid(x): #vector sigmoid
  return 1/(1+np.exp(-x))

sigmoid_numpy(np.array([34,5,6]))

array([1.        , 0.99330715, 0.99752738])

In [39]:

class neural:
    def __init__(self):
        self.W1 = 1
        self.W2 = 1
        self.bias = 0

    def fit(self, x, y, epochs, loss_threshold):
        self.W1, self.W2, self.bias = self.gradient(x['age'], x['affordibility'], y, epochs, loss_threshold)

    def predicts(self, x_test):
        weighted_sum = self.W1 * x_test['age'] + self.W2 * x_test['affordibility'] + self.bias
        return sigmoid(weighted_sum)

    def gradient(self, age, affordability, y_true, epochs, loss_threshold):
        W1 = W2 = 1
        bias = 0
        learning_rate = 0.5
        n = len(age)

        for i in range(epochs):
            weighted_sum = W1 * age + W2 * affordability + bias
            y_pred = sigmoid(weighted_sum)

            loss = log_loss(y_true, y_pred)

            W1_d = (1 / n) * np.dot(np.transpose(age), (y_pred - y_true))
            W2_d = (1 / n) * np.dot(np.transpose(affordability), (y_pred - y_true))

            bias_d = np.mean(y_pred - y_true)

            W1 = W1 - learning_rate * W1_d
            W2 = W2 - learning_rate * W2_d
            bias = bias - learning_rate * bias_d

            print("epoch", i+1, "W1:", W1, "W2:", W2, "bias:", bias, "loss:", loss)

            if loss <= loss_threshold:
                break

        return W1, W2, bias

In [40]:
created_model=neural()
created_model.fit(x_train,y_train,epochs=5,loss_threshold=0)

epoch 1 W1: 0.9736899318847281 W2: 0.931388810977659 bias: -0.11748951666770448 loss: 0.7428288579142563
epoch 2 W1: 0.9536535852311094 W2: 0.8740290167758512 bias: -0.21881533456146035 loss: 0.7072146449948488
epoch 3 W1: 0.9393731039296969 W2: 0.8271852202997496 bias: -0.3053620401943441 loss: 0.6814881914786812
epoch 4 W1: 0.9301932588998061 W2: 0.7897792032048467 bias: -0.37884372361582785 loss: 0.6633428084673968
epoch 5 W1: 0.9254091137248938 W2: 0.7605726653866934 bias: -0.44108236820018304 loss: 0.650742850709519


In [42]:
prediction=created_model.predicts(x_test)

In [43]:
prediction

9     0.707648
25    0.694069
8     0.709559
21    0.450048
0     0.627868
12    0.452340
dtype: float64